appender.console.type=Console
appender.console.name=STDOUT
appender.console.target=SYSTEM_OUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

rootLogger.level=info
rootLogger.appenderRefs=console
rootLogger.appenderRef.console.ref=STDOUT

logger.hibernate.name=org.hibernate.SQL
logger.hibernate.level=debug
logger.hibernate.additivity=false